import os
import json
import subprocess
import re
import getpass
import platform
from fastapi import APIRouter, Request

router = APIRouter()

CURRENT_API_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_API_DIR, "..", ".."))
CONFIG_FILE = os.path.join(PROJECT_ROOT, "data", "deploy_config.json")


@router.get("/config")
async def get_deploy_config():
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            pass
    # 🌟 默认返回双轨结构
    return {
        "blogPath": "",
        "staticRepoUrl": "",
        "staticBranch": "gh-pages",
        "sourceRepoUrl": "",
        "sourceBranch": "main"
    }


@router.post("/config")
async def save_deploy_config(request: Request):
    try:
        data = await request.json()
        os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return {"success": True, "message": "✅ 双轨部署配置已永久保存！"}
    except Exception as e:
        return {"success": False, "message": f"保存失败: {str(e)}"}


# 🔑 核心大升级：根据 type 动态获取/生成不同的 SSH 密匙，并自动配置路由！
@router.get("/ssh/key")
async def get_my_ssh_key(type: str = "static"):
    """获取或生成本地 SSH 公钥 (支持 A/B 双线隔离)"""
    try:
        ssh_dir = os.path.expanduser("~/.ssh")
        os.makedirs(ssh_dir, exist_ok=True)

        # 判断是为 A线(static) 还是 B线(source) 打钥匙
        if type == "source":
            key_name = "id_ed25519_source"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Source"
        else:
            key_name = "id_ed25519"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Static"

        pub_key_path = os.path.join(ssh_dir, f"{key_name}.pub")
        priv_key_path = os.path.join(ssh_dir, key_name)

        # 兼容老用户：如果是 A 线，优先看看有没有老的 id_rsa
        if type == "static" and not os.path.exists(pub_key_path):
            if os.path.exists(os.path.join(ssh_dir, "id_rsa.pub")):
                pub_key_path = os.path.join(ssh_dir, "id_rsa.pub")

        # 如果连指定的钥匙都没有，当场打一把新的！
        if not os.path.exists(pub_key_path):
            subprocess.run([
                "ssh-keygen", "-t", "ed25519",
                "-C", user_tag,
                "-N", "",
                "-f", priv_key_path
            ], check=True)
            pub_key_path = f"{priv_key_path}.pub"

        # 🌟 极客魔法：如果是 B 线(source)，自动在本地注入 SSH 路由分流规则！
        if type == "source":
            config_path = os.path.join(ssh_dir, "config")
            # 兼容 Windows 和 Mac 路径分隔符
            safe_priv_path = priv_key_path.replace('\\', '/')
            config_entry = f"\n# Auto-generated by Blog CMS for Vercel Source Sync\nHost github-source\n    HostName github.com\n    User git\n    IdentityFile {safe_priv_path}\n"

            config_exists = False
            if os.path.exists(config_path):
                with open(config_path, "r", encoding="utf-8") as f:
                    if "Host github-source" in f.read():
                        config_exists = True

            if not config_exists:
                with open(config_path, "a", encoding="utf-8") as f:
                    f.write(config_entry)

        # 读取公钥内容并返回给前端
        with open(pub_key_path, "r", encoding="utf-8") as f:
            key_content = f.read().strip()
            return {"success": True, "key": key_content}

    except Exception as e:
        return {"success": False, "message": f"获取 SSH 失败: {str(e)}"}


@router.post("/check")
async def check_git_env(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "本地物理路径不存在，请先检查路径！"}

        git_dir = os.path.join(blog_path, ".git")
        if not os.path.exists(git_dir):
            return {"success": False, "message": "该路径未初始化 Git 仓库，请点击下方【一键初始化】按钮。"}

        return {"success": True, "message": "✅ Git 环境正常！已准备就绪。"}
    except Exception as e:
        return {"success": False, "message": f"Git 检测失败: {str(e)}"}


@router.post("/init")
async def init_deploy_env(request: Request):
    """初始化双轨部署环境"""
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()
        static_repo = payload.get("staticRepoUrl", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "目标博客路径不存在！"}

        # 1. 基础 Git 初始化
        subprocess.run(["git", "init"], cwd=blog_path, check=True)

        # 为了兼容老版的静态部署插件，我们把 origin 绑定给 A线 (静态仓库)
        if static_repo:
            subprocess.run(["git", "remote", "remove", "origin"], cwd=blog_path, stderr=subprocess.DEVNULL)
            subprocess.run(["git", "remote", "add", "origin", static_repo], cwd=blog_path, check=True)

        # 2. 修改 package.json 写入 scripts (专供 A 线静态发布)
        pkg_path = os.path.join(blog_path, "package.json")
        if os.path.exists(pkg_path):
            with open(pkg_path, "r", encoding="utf-8") as f:
                pkg_data = json.load(f)
            if "scripts" not in pkg_data:
                pkg_data["scripts"] = {}
            pkg_data["scripts"]["deploy"] = "next build && gh-pages -d out"
            with open(pkg_path, "w", encoding="utf-8") as f:
                json.dump(pkg_data, f, indent=2, ensure_ascii=False)

        # 3. 安装 gh-pages 插件
        process = subprocess.Popen(
            ["npm", "install", "gh-pages", "--save-dev"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()

        return {"success": True, "message": "✨ 太棒了！双轨部署底层依赖与配置初始化完成！"}
    except Exception as e:
        return {"success": False, "message": f"初始化发生异常: {str(e)}"}


# 🔄 一键部署：构建 → 复制 → 推送 gh-pages
@router.post("/trigger-workflow")
async def trigger_workflow():
    """完整部署流程: npm build → 复制out/到XHBlogs → git push gh-pages"""
    import shutil
    try:
        # 读取配置
        if not os.path.exists(CONFIG_FILE):
            return {"success": False, "message": "未找到 deploy_config.json"}
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)
        blog_path = config.get("blogPath", "").strip()
        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": f"blogPath 不存在或为空: {blog_path}"}

        # Step 1: 临时移除 app/api（静态导出不支持动态 API 路由）
        api_dir = os.path.join(PROJECT_ROOT, "app", "api")
        api_backup = os.path.join(PROJECT_ROOT, "app", "_api_backup")
        api_moved = False
        if os.path.exists(api_dir):
            os.rename(api_dir, api_backup)
            api_moved = True
            print(f"[Deploy] Step1a: moved app/api -> app/_api_backup")

        try:
            # Step 2: npm run build
            print(f"[Deploy] Step1b: building Next.js at {PROJECT_ROOT}...")
            build_result = subprocess.run(
                ["npm", "run", "build"],
                cwd=PROJECT_ROOT,
                capture_output=True,
                text=True,
                encoding="utf-8",
                timeout=300,
                shell=True
            )
            if build_result.returncode != 0:
                return {"success": False, "message": f"构建失败:\n{build_result.stderr[-2000:]}"}
            print(f"[Deploy] Step1b: build OK")
        finally:
            # 恢复 app/api
            if api_moved:
                os.rename(api_backup, api_dir)
                print(f"[Deploy] Step1c: restored app/api")

        # Step 2: 清空 blog_path (保留 .git) 并复制 out/*
        out_dir = os.path.join(blog_path, "dist")
        if not os.path.exists(out_dir):
            return {"success": False, "message": f"out/ 目录不存在: {out_dir}"}
        print(f"[Deploy] Step2: copying {out_dir} -> {blog_path}...")
        for item in os.listdir(blog_path):
            item_path = os.path.join(blog_path, item)
            if item == ".git": continue
            if os.path.isdir(item_path):
                shutil.rmtree(item_path)
            else:
                os.remove(item_path)
        for item in os.listdir(out_dir):
            src = os.path.join(out_dir, item)
            dst = os.path.join(blog_path, item)
            if os.path.isdir(src):
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)
        print(f"[Deploy] Step2: copy OK")

        # Step 3: git checkout gh-pages → add → commit → push → checkout main
        print(f"[Deploy] Step3: git push to gh-pages...")
        subprocess.run(["git", "checkout", "gh-pages"], cwd=blog_path, check=True, capture_output=True, shell=True)
        subprocess.run(["git", "add", "."], cwd=blog_path, check=True, capture_output=True, shell=True)
        commit_result = subprocess.run(
            ["git", "commit", "-m", "auto-deploy from CMS"],
            cwd=blog_path, capture_output=True, text=True, shell=True
        )
        push_result = subprocess.run(
            ["git", "push", "origin", "gh-pages"],
            cwd=blog_path, capture_output=True, text=True, timeout=120, shell=True
        )
        subprocess.run(["git", "checkout", "main"], cwd=blog_path, capture_output=True, shell=True)

        if push_result.returncode != 0 and "Everything up-to-date" not in push_result.stderr:
            return {"success": False, "message": f"git push 失败:\n{push_result.stderr}"}

        return {"success": True, "message": "🎉 部署成功！构建→复制→推送全部完成，GitHub Pages 将自动更新。"}
    except subprocess.TimeoutExpired:
        return {"success": False, "message": "操作超时（可能是构建或push太慢）"}
    except Exception as e:
        return {"success": False, "message": f"部署异常: {str(e)}"}


# 🚀 A 线接口：打包静态文件并发布到 GitHub Pages
@router.post("/publish")
async def publish_to_github_pages(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        process = subprocess.Popen(
            ["npm", "run", "deploy"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()
        if process.returncode == 0:
            return {"success": True, "message": "🎉 A线: 网页已成功编译并发布到静态仓库！"}
        else:
            return {"success": False, "message": f"发布失败，报错:\n{stderr}"}
    except Exception as e:
        return {"success": False, "message": f"静态发布引擎崩溃: {str(e)}"}


# ☁️ B 线接口：同步源代码到 GitHub → Vercel 自动构建
@router.post("/source")
async def sync_source_to_vercel(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        # 读取配置
        if not os.path.exists(CONFIG_FILE):
            return {"success": False, "message": "未找到配置文件，请先点击保存！"}

        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)

        source_repo = config.get("sourceRepoUrl", "").strip()
        source_branch = config.get("sourceBranch", "main").strip()

        if not source_repo:
            return {"success": False, "message": "B 线源码仓库地址为空，无法同步！"}

        # 确保 repo URL 是 HTTPS 格式
        if source_repo.startswith("git@"):
            # git@github.com:user/repo.git → https://github.com/user/repo.git
            source_repo = source_repo.replace("git@github.com:", "https://github.com/").replace(".git", ".git")

        # 1. 确保在 my-blog-manager 目录下操作
        work_dir = PROJECT_ROOT

        # 2. git add
        subprocess.run(["git", "add", "."], cwd=work_dir, capture_output=True, shell=True)

        # 3. git commit（无改动时跳过）
        subprocess.run(
            ["git", "commit", "-m", "Auto sync source code for Vercel"],
            cwd=work_dir, capture_output=True, shell=True
        )

        # 4. 确保 remote origin 指向正确的 HTTPS 仓库
        subprocess.run(["git", "remote", "remove", "origin"], cwd=work_dir, capture_output=True, shell=True)
        subprocess.run(
            ["git", "remote", "add", "origin", source_repo],
            cwd=work_dir, check=True, capture_output=True, shell=True
        )

        # 5. git push（HTTPS + PAT，凭证由 credential.helper manager 提供）
        push_result = subprocess.run(
            ["git", "push", "origin", f"HEAD:{source_branch}", "--force"],
            cwd=work_dir, capture_output=True, text=True, encoding="utf-8", timeout=120, shell=True
        )

        if push_result.returncode != 0 and "Everything up-to-date" not in push_result.stdout and "Everything up-to-date" not in push_result.stderr:
            return {"success": False, "message": f"源码同步失败:\n{push_result.stdout[-1500:]}\n{push_result.stderr[-1500:]}"}

        return {"success": True, "message": "☁️ B线: 源码已成功推送到 GitHub，Vercel 将自动构建部署！"}

    except subprocess.TimeoutExpired:
        return {"success": False, "message": "推送超时，请检查网络连接"}
    except Exception as e:
        return {"success": False, "message": f"源码同步引擎异常: {str(e)}"}